"""empty message

Revision ID: 1c83d3a73c76
Revises: 5d77b4cb64ed
Create Date: 2017-11-07 22:27:01.399898

"""

# revision identifiers, used by Alembic.
revision = '1c83d3a73c76'
down_revision = '5d77b4cb64ed'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_anmeldung():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_anmeldung():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_stapf():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('decided', sa.Date(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_table('decision_recipients_lists',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('recipients_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_decision_recipients_lists_decision_id_decisions')),
    sa.ForeignKeyConstraint(['recipients_list_id'], ['recipients_lists.id'], name=op.f('fk_decision_recipients_lists_recipients_list_id_recipients_lists')),
    sa.PrimaryKeyConstraint('decision_id', 'recipients_list_id', name=op.f('pk_decision_recipients_lists'))
    )
    # ### end Alembic commands ###


def downgrade_stapf():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_recipients_lists')
    op.drop_table('decisions')
    # ### end Alembic commands ###

