"""empty message

Revision ID: 5d77b4cb64ed
Revises: 
Create Date: 2017-11-05 18:23:46.917467

"""

# revision identifiers, used by Alembic.
revision = '5d77b4cb64ed'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_anmeldung():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('slots', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uni')),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('token')
    )
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('blob', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('uni_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uni_id'], ['uni.id'], name=op.f('fk_registration_uni_id_uni')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registration')),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade_anmeldung():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration')
    op.drop_table('uni')
    # ### end Alembic commands ###


def upgrade_stapf():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('organisation_name', sa.Text(), nullable=True),
    sa.Column('addressline1', sa.Text(), nullable=True),
    sa.Column('addressline2', sa.Text(), nullable=True),
    sa.Column('street', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('locality', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('mail', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipients'))
    )
    op.create_table('recipients_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipients_lists')),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipient_to_list',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], name=op.f('fk_recipient_to_list_recipient_id_recipients')),
    sa.ForeignKeyConstraint(['list_id'], ['recipients_lists.id'], name=op.f('fk_recipient_to_list_list_id_recipients_lists')),
    sa.PrimaryKeyConstraint('list_id', 'recipient_id', name=op.f('pk_recipient_to_list'))
    )
    # ### end Alembic commands ###


def downgrade_stapf():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipient_to_list')
    op.drop_table('recipients_lists')
    op.drop_table('recipients')
    # ### end Alembic commands ###

